name: Auto Merge main into br1

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

# Define global permissions for all jobs
permissions:
  pull-requests: write  # Gives write access to pull requests (needed for merging)
  contents: write        # Gives write access to repository contents

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'br1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto merge PR if author is correct
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const allowedAuthor = 'sakshi-chauhan-maersk';  // Replace with allowed GitHub username

            if (pr.head.ref === 'br1' && pr.base.ref === 'main' && pr.user.login === allowedAuthor) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'merge',
              });
            } else {
              console.log('PR not merged: either the branch or author did not match.');
            }
